import { iItem } from "../interfaces"

 export const ListItemMock:iItem  = {
    adult: false,
    backdrop_path: "/wevFeIpfABIcswMKjotI8p59hT7.jpg",
    id: 687280,
    original_language:"en",
    original_title:"Salam dari Kepiting Selatan",
    overview:"A father's death is imminent, but the rest of the family tries to live and communicate as usual despite it.",
    popularity:0.6,
    poster_path:"https://image.tmdb.org/t/p/w500/wevFeIpfABIcswMKjotI8p59hT7.jpg",
    release_date:"2017-06-12",
    title:"Regards from the Southern Crab",
    video: false,
    vote_average:5,
    vote_count:50,
    isFavourite:false,
    isWatchLater:false
  } 


  export const ItemListMock: iItem[] = [
    {
        adult: false,
        backdrop_path: "/snDGwQ3fbfNiGwUfT7dVPQ4MTSV.jpg",
        id: 117352,
        original_language: "ja",
        original_title: "クレヨンしんちゃん 超時空！嵐を呼ぶオラの花嫁",
        overview: "Shin-chan is approached by his time-traveling future bride-to-be Tamiko, who asks him to help save his adult self from the ruler of Neo Tokio.",
        popularity: 18.925,
        poster_path: "/qHyfSoMeGk2x5gxeXq03GiKk5a4.jpg",
        release_date: "2010-04-17",
        title: "Crayon Shin-chan: Super-Dimension! The Storm Called My Bride",
        video: false,
        vote_average: 8.1,
        vote_count: 34,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
        id: 299537,
        original_language: "en",
        original_title: "Captain Marvel",
        overview: "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
        popularity: 91.798,
        poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
        release_date: "2019-03-06",
        title: "Captain Marvel",
        video: false,
        vote_average: 6.9,
        vote_count: 13588,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/45Jpw4XHa95GoXKKUlQQSP1PgvK.jpg",
        id: 211387,
        original_language: "en",
        original_title: "Marvel One-Shot: Agent Carter",
        overview: "The film takes place one year after the events of Captain America: The First Avenger, in which Agent Carter, a member of the Strategic Scientific Reserve, is in search of the mysterious Zodiac.",
        popularity: 26.768,
        poster_path: "/4vFKKWPvCVDJTOWiwReBfpAMScP.jpg",
        release_date: "2013-09-03",
        title: "Marvel One-Shot: Agent Carter",
        video: false,
        vote_average: 7.3,
        vote_count: 593,
        isFavourite: false,
        isWatchLater:false
    },
    {
        "adult": false,
        backdrop_path: "/h7fyYm1VXCivGtNx6TfEj1AVObI.jpg",
        id: 76122,
        original_language: "en",
        original_title: "Marvel One-Shot: The Consultant",
        overview: "Agent Coulson informs Agent Sitwell that the World Security Council wishes Emil Blonsky to be released from prison to join the Avengers Initiative. As Nick Fury doesn't want to release Blonsky, the two agents decide to send a patsy to sabotage the meeting...",
        popularity: 22.071,
        poster_path: "/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
        release_date: "2011-09-13",
        title: "Marvel One-Shot: The Consultant",
        video: false,
        vote_average: 6.4,
        vote_count: 403,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/95AKEQdhAF7YlH6XJSOFaqNTW0J.jpg",
        id: 491633,
        original_language: "en",
        original_title: "Marvel Rising: Secret Warriors",
        overview: "When a threat no one could have expected bears down on the Marvel Universe, this ragtag, untrained band of teens have no choice but to rise together and prove to the world that sometimes the difference between a 'hero' and 'misfit' is just in the name.",
        popularity: 18.974,
        poster_path: "/kY1ufnbv2bTyoNcAtGF4BwapKi6.jpg",
        release_date: "2018-09-30",
        title: "Marvel Rising: Secret Warriors",
        video: false,
        vote_average: 6.8,
        vote_count: 75,
        isFavourite: false,
        isWatchLater:false
    }
];



    export const ItemListWithResultMock = {"page":1,"results": [
    {
        adult: false,
        backdrop_path: "/snDGwQ3fbfNiGwUfT7dVPQ4MTSV.jpg",
        id: 117352,
        original_language: "ja",
        original_title: "クレヨンしんちゃん 超時空！嵐を呼ぶオラの花嫁",
        overview: "Shin-chan is approached by his time-traveling future bride-to-be Tamiko, who asks him to help save his adult self from the ruler of Neo Tokio.",
        popularity: 18.925,
        poster_path: "/qHyfSoMeGk2x5gxeXq03GiKk5a4.jpg",
        release_date: "2010-04-17",
        title: "Crayon Shin-chan: Super-Dimension! The Storm Called My Bride",
        video: false,
        vote_average: 8.1,
        vote_count: 34,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg",
        id: 299537,
        original_language: "en",
        original_title: "Captain Marvel",
        overview: "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
        popularity: 91.798,
        poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
        release_date: "2019-03-06",
        title: "Captain Marvel",
        video: false,
        vote_average: 6.9,
        vote_count: 13588,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/45Jpw4XHa95GoXKKUlQQSP1PgvK.jpg",
        id: 211387,
        original_language: "en",
        original_title: "Marvel One-Shot: Agent Carter",
        overview: "The film takes place one year after the events of Captain America: The First Avenger, in which Agent Carter, a member of the Strategic Scientific Reserve, is in search of the mysterious Zodiac.",
        popularity: 26.768,
        poster_path: "/4vFKKWPvCVDJTOWiwReBfpAMScP.jpg",
        release_date: "2013-09-03",
        title: "Marvel One-Shot: Agent Carter",
        video: false,
        vote_average: 7.3,
        vote_count: 593,
        isFavourite: false,
        isWatchLater:false
    },
    {
        "adult": false,
        backdrop_path: "/h7fyYm1VXCivGtNx6TfEj1AVObI.jpg",
        id: 76122,
        original_language: "en",
        original_title: "Marvel One-Shot: The Consultant",
        overview: "Agent Coulson informs Agent Sitwell that the World Security Council wishes Emil Blonsky to be released from prison to join the Avengers Initiative. As Nick Fury doesn't want to release Blonsky, the two agents decide to send a patsy to sabotage the meeting...",
        popularity: 22.071,
        poster_path: "/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
        release_date: "2011-09-13",
        title: "Marvel One-Shot: The Consultant",
        video: false,
        vote_average: 6.4,
        vote_count: 403,
        isFavourite: false,
        isWatchLater:false
    },
    {
        adult: false,
        backdrop_path: "/95AKEQdhAF7YlH6XJSOFaqNTW0J.jpg",
        id: 491633,
        original_language: "en",
        original_title: "Marvel Rising: Secret Warriors",
        overview: "When a threat no one could have expected bears down on the Marvel Universe, this ragtag, untrained band of teens have no choice but to rise together and prove to the world that sometimes the difference between a 'hero' and 'misfit' is just in the name.",
        popularity: 18.974,
        poster_path: "/kY1ufnbv2bTyoNcAtGF4BwapKi6.jpg",
        release_date: "2018-09-30",
        title: "Marvel Rising: Secret Warriors",
        video: false,
        vote_average: 6.8,
        vote_count: 75,
        isFavourite: false,
        isWatchLater:false
    }
]
    };
 